const express=require('express');
const multer=require('multer');
const fs=require('fs');
const os=require('os');
const path=require('path');
const https=require('https');

const app=express();
const PORT=process.env.PORT||10000;
const REPO=process.env.REPO_FULL_NAME||'nusratbytxrs/release-hosting';
const SITE_NAME=process.env.SITE_NAME||'Release Hosting';
const TOKEN=process.env.GITHUB_TOKEN;
const ADMIN_KEY=process.env.ADMIN_KEY;
const MAX_MB=Number(process.env.MAX_UPLOAD_MB||500);
const MAX_BYTES=MAX_MB*1024*1024;
const upload=multer({dest:os.tmpdir(),limits:{fileSize:MAX_BYTES}});
app.use(express.json());

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const safe=v=>path.basename(String(v||'').replace(/[\\/]/g,''));
const ext=v=>(safe(v).match(/(\.[^.]+)$/i)||['',''])[1].toLowerCase();
const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return`${x>=10||i===0?x.toFixed(0):x.toFixed(1)} ${u[i]}`};

async function gh(endpoint,options={}){if(!TOKEN)throw Error('GITHUB_TOKEN is not configured.');const r=await fetch(`https://api.github.com${endpoint}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${TOKEN}`,'User-Agent':'release-hosting',...(options.headers||{})}});const text=await r.text();let data;try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok){const e=Error(data.message||`GitHub request failed (${r.status})`);e.status=r.status;throw e}return data}
const releases=()=>gh(`/repos/${REPO}/releases?per_page=100`);
const release=tag=>gh(`/repos/${REPO}/releases/tags/${encodeURIComponent(tag)}`);
function auth(req,res,next){const key=req.get('x-admin-key')||req.body?.adminKey||req.query?.adminKey;if(!ADMIN_KEY||key!==ADMIN_KEY)return res.status(401).json({ok:false,error:'Unauthorized.'});next()}
function uploadAsset(id,name,type,file){return new Promise((resolve,reject)=>{const stat=fs.statSync(file);const q=https.request({hostname:'uploads.github.com',method:'POST',path:`/repos/${REPO}/releases/${encodeURIComponent(id)}/assets?name=${encodeURIComponent(name)}`,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${TOKEN}`,'User-Agent':'release-hosting','Content-Type':type||'application/octet-stream','Content-Length':stat.size}},r=>{let body='';r.setEncoding('utf8');r.on('data',c=>body+=c);r.on('end',()=>{let data;try{data=JSON.parse(body)}catch{data={message:body}}if(r.statusCode>=200&&r.statusCode<300)resolve(data);else reject(Error(data.message||`Upload failed (${r.statusCode})`))})});q.on('error',reject);fs.createReadStream(file).on('error',reject).pipe(q)})}
function page(title,body,script=''){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} - ${esc(SITE_NAME)}</title><style>:root{--bg:#08090d;--panel:#11141c;--panel2:#191d28;--line:#293141;--text:#f8fafc;--muted:#9aa5b5;--accent:#7c5cff;--danger:#ff8c8c;--ok:#42dca2}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px system-ui,sans-serif}a{color:#a99aff;text-decoration:none}.wrap{max-width:1100px;margin:auto;padding:22px 18px 50px}.top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding:12px 0 18px;margin-bottom:22px}.nav{display:flex;gap:10px}.pill,button,input,select{border:1px solid var(--line);border-radius:9px;background:var(--panel2);color:inherit;padding:9px 12px;font:inherit}.pill{display:inline-block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.card,.panel,.upload-row,.asset{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:13px;padding:16px}.muted{color:var(--muted)}.error{color:var(--danger)}.ok{color:var(--ok)}label{display:block;color:var(--muted);margin:12px 0}input,select{display:block;width:100%;margin-top:6px}.primary{background:var(--accent);border-color:var(--accent);cursor:pointer}.upload-row{display:flex;align-items:center;gap:12px;margin-top:10px}.main{flex:1;min-width:0}.name{font-weight:700;overflow-wrap:anywhere}.status{display:block;color:var(--muted);font-size:.9rem;margin-top:5px}.progress{height:9px;border-radius:10px;background:#293141;overflow:hidden;margin-top:8px}.progress i{display:block;height:100%;width:0;background:var(--accent)}.danger{color:var(--danger);cursor:pointer}.asset{display:flex;justify-content:space-between;gap:12px;margin-top:9px}@media(max-width:600px){.top{align-items:flex-start;gap:15px;flex-direction:column}.nav{width:100%}}</style></head><body><div class="wrap"><header class="top"><b><a href="/">${esc(SITE_NAME)}</a></b><nav class="nav"><a class="pill" href="/">Releases</a><a class="pill" href="/admin">Admin</a></nav></header>${body}</div><script>${script}</script></body></html>`}
function assetsHtml(items){return items.length?`<div class="panel"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><b>Release files</b><select id="sort" style="width:auto"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="smallest">Smallest first</option><option value="largest">Largest first</option></select></div><div id="assets">${items.map(a=>`<div class="asset" data-date="${esc(a.created_at||'')}" data-size="${a.size||0}"><div><a href="${esc(a.browser_download_url||'#')}" target="_blank">${esc(a.name)}</a><br><small class="muted">${bytes(a.size)} · ${new Date(a.created_at||Date.now()).toLocaleString()}</small></div><small class="muted">${esc(a.content_type||'file')}</small></div>`).join('')}</div></div>`:'<div class="panel muted">No files in this release yet.</div>'}

app.get('/',async(_q,res)=>{try{const rs=await releases();const cards=rs.filter(r=>!r.draft).map(r=>`<div class="card"><h2><a href="/release/${encodeURIComponent(r.tag_name)}">${esc(r.name||r.tag_name)}</a></h2><p class="muted">${esc(r.tag_name)}</p><p>${(r.assets||[]).length} file(s)</p></div>`).join('');res.send(page('Releases',`<h1>Latest releases</h1><div class="grid">${cards}</div>`))}catch(e){res.status(500).send(page('Error',`<div class="panel error">${esc(e.message)}</div>`))}});
app.get('/release/:tag',async(req,res)=>{try{const r=await release(req.params.tag);const script=`const s=document.getElementById('sort'),box=document.getElementById('assets');if(s&&box)s.onchange=()=>{const a=[...box.children];a.sort((x,y)=>s.value==='newest'?new Date(y.dataset.date)-new Date(x.dataset.date):s.value==='oldest'?new Date(x.dataset.date)-new Date(y.dataset.date):s.value==='smallest'?+x.dataset.size-+y.dataset.size:+y.dataset.size-+x.dataset.size);a.forEach(x=>box.appendChild(x))}`;res.send(page(r.name||r.tag_name,`<div class="panel"><a href="/">← Back to releases</a><h1>${esc(r.name||r.tag_name)}</h1><p class="muted">${esc(r.tag_name)}</p></div>${assetsHtml(r.assets||[])}`,script))}catch(e){res.status(404).send(page('Not found',`<div class="panel error">${esc(e.message)}</div>`))}});
app.get('/api/releases',async(_q,res)=>{try{const rs=await releases();res.json({ok:true,count:rs.length,releases:rs})}catch(e){res.status(e.status||500).json({ok:false,error:e.message})}});
app.get('/admin',async(_q,res)=>{try{const rs=await releases();const opts=rs.filter(r=>!r.draft).map(r=>`<option value="${esc(r.id)}">${esc(r.name||r.tag_name)} (${esc(r.tag_name)})</option>`).join('');const body=`<div class="panel"><h1>Upload release asset</h1><p class="muted">Maximum file size: ${MAX_MB} MB</p><form id="form"><label>Admin key<input id="key" type="password" required></label><label>Release<select id="rel" required>${opts}</select></label><label>Files<input id="files" type="file" multiple required></label><button class="primary" type="submit">Upload files</button></form></div><div id="queue"></div>`;const script=`const form=document.getElementById('form'),files=document.getElementById('files'),queue=document.getElementById('queue'),key=document.getElementById('key'),rel=document.getElementById('rel');function speed(n,t){const x=n/Math.max(t/1000,.001);return x>=1048576?(x/1048576).toFixed(1)+' MB/s':(x/1024).toFixed(0)+' KB/s'}function start(file){const row=document.createElement('div');row.className='upload-row';const main=document.createElement('div');main.className='main';const name=document.createElement('div');name.className='name';name.textContent=file.name;const status=document.createElement('span');status.className='status';status.textContent='Preparing…';const progress=document.createElement('div');progress.className='progress';const bar=document.createElement('i');progress.appendChild(bar);main.append(name,status,progress);const cancel=document.createElement('button');cancel.className='danger';cancel.type='button';cancel.textContent='✕';row.append(main,cancel);queue.prepend(row);if(file.size>${MAX_BYTES}){status.textContent='File exceeds the ${MAX_MB} MB limit.';status.classList.add('error');cancel.remove();return}const fd=new FormData();fd.append('file',file);fd.append('releaseId',rel.value);const xhr=new XMLHttpRequest(),started=performance.now();xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded/e.total*100);bar.style.width=p+'%';status.textContent=p+'% · '+speed(e.loaded,performance.now()-started)}};xhr.onload=()=>{let d={};try{d=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300&&d.ok){bar.style.width='100%';status.textContent='Uploaded ✓';status.classList.add('ok')}else{status.textContent=d.error||'Upload failed';status.classList.add('error')}};xhr.onerror=()=>{status.textContent='Network error';status.classList.add('error')};xhr.onabort=()=>{status.textContent='Cancelled';status.classList.add('error');bar.style.width='0'};cancel.onclick=()=>xhr.abort();xhr.open('POST','/api/upload');xhr.setRequestHeader('x-admin-key',key.value);xhr.send(fd)}form.onsubmit=e=>{e.preventDefault();[...files.files].forEach(start)}`;res.send(page('Admin',body,script))}catch(e){res.status(500).send(page('Error',`<div class="panel error">${esc(e.message)}</div>`))}});
app.post('/api/upload',auth,(req,res,next)=>upload.single('file')(req,res,err=>{if(err){if(err.code==='LIMIT_FILE_SIZE')return res.status(413).json({ok:false,error:`File exceeds the ${MAX_MB} MB upload limit.`});return res.status(400).json({ok:false,error:err.message})}next()}),async(req,res)=>{const tmp=req.file?.path;try{if(!req.file||!req.body.releaseId)return res.status(400).json({ok:false,error:'File and release are required.'});const name=safe(req.file.originalname);if(!name)return res.status(400).json({ok:false,error:'A valid filename is required.'});res.json({ok:true,asset:await uploadAsset(req.body.releaseId,name,req.file.mimetype,tmp)})}catch(e){res.status(e.status||500).json({ok:false,error:e.message})}finally{if(tmp)fs.promises.unlink(tmp).catch(()=>{})}});
app.patch('/api/assets/:id',auth,async(req,res)=>{try{const a=await gh(`/repos/${REPO}/releases/assets/${req.params.id}`),old=ext(a.name),requested=safe(req.body?.name);if(!requested)return res.status(400).json({ok:false,error:'A valid filename is required.'});const next=ext(requested);if(old&&next&&old!==next)return res.status(400).json({ok:false,error:`The file extension must remain ${old}.`});const name=old&&!next?requested+old:requested;res.json({ok:true,asset:await gh(`/repos/${REPO}/releases/assets/${req.params.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})})}catch(e){res.status(e.status||500).json({ok:false,error:e.message})}});
app.get('/health',(_q,res)=>res.json({ok:true,maxUploadMb:MAX_MB}));
app.listen(PORT,()=>console.log(`${SITE_NAME} listening on ${PORT}`));
